version: '3'

services:
  backend:
    build: ./backend-express
    expose:
      - 4011
    ports:
      - '4011:4011'

  frontend:
    build: ./frontend-react
    expose:
      - 5011
    ports:
      - 5011:5011
    depends_on: 
      - backend
    volumes:
      - ./frontend-react/src:/app/src  




